<?php

namespace App\Http\Requests\Payment;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Validator;

/**
 * ============================================================
 * VerifyPaymentRequest
 * ============================================================
 *
 * Validates the request to VERIFY a payment after the user
 * has completed the Razorpay checkout flow in the Flutter app.
 *
 * RAZORPAY VERIFICATION FLOW:
 *   1. Server calls initiate() → creates Razorpay order
 *      → returns razorpay_order_id to Flutter
 *   2. Flutter opens Razorpay SDK with the order_id
 *   3. User completes payment in Razorpay's native UI
 *   4. Razorpay SDK returns to Flutter:
 *        - razorpay_payment_id  (e.g. "pay_AbCdEf123456")
 *        - razorpay_order_id    (same as step 1)
 *        - razorpay_signature   (HMAC SHA256 hash for verification)
 *   5. Flutter calls POST /api/v1/payments/verify with these three values
 *   6. Server verifies the signature (proves payment is genuine)
 *   7. If valid → booking confirmed, QR generated
 *
 * WHY IS SIGNATURE VERIFICATION CRITICAL?
 * Without verifying the signature, a malicious user could simply
 * craft a fake API call with a made-up payment_id and claim their
 * booking is paid. The HMAC signature can only be generated by
 * Razorpay's servers using our secret key — so it proves the
 * payment genuinely happened.
 *
 * SIGNATURE ALGORITHM (for reference in PaymentController):
 *   $signature = hash_hmac(
 *       'sha256',
 *       $razorpay_order_id . '|' . $razorpay_payment_id,
 *       config('services.razorpay.key_secret')
 *   );
 *   if ($signature !== $razorpay_signature) → reject
 *
 * FUTURE SCALABILITY:
 *   - Add `metadata` JSON field for custom data the Flutter app
 *     might want to pass back (e.g. device info for fraud analysis).
 *   - When supporting multiple gateways (PayU, Stripe), add a
 *     `gateway` field to route verification to the correct handler.
 */
class VerifyPaymentRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    public function rules(): array
    {
        return [
            // Our internal payment record ID — created during initiate().
            // Used to find the booking and update the payment record.
            'payment_id' => [
                'required',
                'integer',
                \Illuminate\Validation\Rule::exists('payments', 'id'),
            ],

            // Razorpay's unique payment identifier.
            // Format: "pay_" followed by alphanumeric characters.
            // Example: "pay_AbCdEf1234567890"
            'razorpay_payment_id' => [
                'required',
                'string',
                'min:10',
                'max:100',
            ],

            // The order ID we created during initiate() and stored
            // in our payments table. Must match what Razorpay returns.
            'razorpay_order_id' => [
                'required',
                'string',
                'min:10',
                'max:100',
            ],

            // HMAC SHA256 signature from Razorpay.
            // Critical for security — proves the payment is genuine.
            // Server verifies this against our Razorpay secret key.
            'razorpay_signature' => [
                'required',
                'string',
                'min:10',
            ],
        ];
    }

    /**
     * Additional validation: ensure the payment_id belongs to
     * the requesting user and is in the expected state.
     *
     * @param  Validator  $validator
     */
    public function withValidator(Validator $validator): void
    {
        $validator->after(function (Validator $v) {

            if ($v->errors()->any()) {
                return;
            }

            $paymentId = $this->input('payment_id');
            $userId    = $this->user()->id;

            $payment = \App\Models\Payment::with('booking')->find($paymentId);

            if (!$payment) {
                $v->errors()->add('payment_id', 'Payment record not found.');
                return;
            }

            // Ensure the payment belongs to this user.
            if ($payment->user_id !== $userId) {
                $v->errors()->add('payment_id', 'This payment does not belong to your account.');
                return;
            }

            // Payment must be in "pending" status.
            // "success" means already verified. "failed" means retry.
            if ($payment->status === 'success') {
                $v->errors()->add('payment_id', 'This payment has already been verified and confirmed.');
                return;
            }

            if ($payment->status === 'refunded') {
                $v->errors()->add('payment_id', 'This payment has already been refunded.');
                return;
            }

            // The razorpay_order_id in the request must match what
            // we stored when we created the order in initiate().
            // This prevents someone submitting a valid payment for a
            // different order against this booking.
            if ($payment->razorpay_order_id !== $this->input('razorpay_order_id')) {
                $v->errors()->add(
                    'razorpay_order_id',
                    'The Razorpay order ID does not match our records for this payment.'
                );
            }
        });
    }

    public function messages(): array
    {
        return [
            'payment_id.required'           => 'Payment ID is required for verification.',
            'payment_id.exists'             => 'The specified payment record does not exist.',
            'razorpay_payment_id.required'  => 'Razorpay payment ID is required.',
            'razorpay_payment_id.min'       => 'Invalid Razorpay payment ID format.',
            'razorpay_order_id.required'    => 'Razorpay order ID is required.',
            'razorpay_order_id.min'         => 'Invalid Razorpay order ID format.',
            'razorpay_signature.required'   => 'Razorpay payment signature is required for security verification.',
            'razorpay_signature.min'        => 'Invalid signature format.',
        ];
    }
}