<?php

namespace App\Http\Resources;

use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

/**
 * ============================================================
 * ParkingImageResource
 * ============================================================
 *
 * Transforms a ParkingImage model into a clean JSON response.
 * The Flutter app uses `url` to display images in the gallery.
 */
class ParkingImageResource extends JsonResource
{
    /**
     * @return array<string, mixed>
     */
    public function toArray(Request $request): array
    {
        return [
            'id'         => $this->id,
            'parking_id' => $this->parking_id,

            /**
             * Full public URL to the image.
             * Generated by the `url` accessor on the ParkingImage model:
             *   Storage::url($this->image_path)
             * Works with both local storage and S3.
             */
            'url'        => $this->url,

            'is_primary' => (bool) $this->is_primary,
            'created_at' => $this->created_at?->toISOString(),
        ];
    }
}
