<?php

namespace App\Http\Resources;

use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

/**
 * ============================================================
 * VehicleDocumentResource
 * ============================================================
 *
 * Transforms a VehicleDocument model into a structured JSON response.
 *
 * EXPIRY AWARENESS:
 *   The resource exposes computed expiry flags so the Flutter app
 *   can show warning/error badges without implementing date logic:
 *     - is_valid:       true if status=active AND not past expiry
 *     - is_expired:     true if expiry_date is in the past
 *     - days_until_expiry: integer (negative if already expired, null if no expiry)
 *
 * FILE ACCESS:
 *   document_path is the internal storage path.
 *   url is the full public URL (via Storage::url accessor on the model).
 *   The Flutter app uses `url` to display or download the document.
 */
class VehicleDocumentResource extends JsonResource
{
    /**
     * @return array<string, mixed>
     */
    public function toArray(Request $request): array
    {
        return [
            // ── IDENTITY ──────────────────────────────────────────────────
            'id'         => $this->id,
            'vehicle_id' => $this->vehicle_id,

            // ── DOCUMENT TYPE ──────────────────────────────────────────────
            'document_type'  => $this->document_type,

            /**
             * Human-readable label from model accessor.
             * e.g. 'insurance' → 'Insurance Certificate'
             * Saves the Flutter app from doing its own type mapping.
             */
            'type_label'     => $this->type_label,

            // ── FILE ACCESS ────────────────────────────────────────────────
            /**
             * Full public URL to the document file.
             * Generated by Storage::url($this->document_path).
             * Works with local disk and S3 (reads FILESYSTEM_DISK from .env).
             */
            'url' => $this->url,

            // ── VALIDITY ───────────────────────────────────────────────────
            'expiry_date'      => $this->expiry_date?->toDateString(), // "2026-01-15"
            'status'           => $this->status,
            'is_valid'         => $this->isValid(),
            'is_expired'       => $this->isExpired(),

            /**
             * How many days until expiry.
             * null = no expiry date (e.g. RC)
             * positive integer = days remaining
             * negative integer = already expired N days ago
             *
             * Flutter uses this for: warning badges (< 30 days), error badges (< 0 days).
             */
            'days_until_expiry' => $this->daysUntilExpiry(),

            // ── VEHICLE (when accessed standalone, not nested) ─────────────
            'vehicle' => $this->whenLoaded('vehicle', fn () => [
                'id'             => $this->vehicle->id,
                'vehicle_name'   => $this->vehicle->vehicle_name,
                'vehicle_number' => $this->vehicle->vehicle_number,
            ]),

            // ── TIMESTAMPS ─────────────────────────────────────────────────
            'created_at' => $this->created_at?->toISOString(),
            'updated_at' => $this->updated_at?->toISOString(),
        ];
    }
}